---
# tasks file for roles/bastion
### Копируем ключ id_rsa из домашней директории в пересенну ssh_priv_keys
- name: fetch ssh keys
  become: false
  shell: cat ~/.ssh/id_rsa
  register: ssh_priv_keys
  connection: local
### Создание файла id_rsa в каталоге linux_user (из vars.tf)
- name: Creating a file with content
  become_user: "{{ linux_user }}"
  become: false
  copy:
    mode: 0600
    dest: "/home/{{ linux_user }}/.ssh/id_rsa"
    content: |
        {{ ssh_priv_keys.stdout }}
######## Проверка наличия YC CLI
- name: Check that bin YC CLI exist
  stat:
    path: /home/{{ linux_user }}/yandex-cloud/bin/yc
  register: stat_result
######## Установка YC CLI https://cloud.yandex.com/en/docs/cli/operations/install-cli
- name: YC CLI install
  become: false
  shell: curl -sL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
  when: not stat_result.stat.exists
### Создание каталога для конфигурация YC
- name: YC CLI Create config dir
  file:
    path: "root/.config/yandex-cloud/"
    state: directory
    mode: 0755
    recurse: yes
### Создание файла конфигурации с параметрами доступа yc cli
- name: YC CLI copy config
  become: true
  become_user: "{{ linux_user }}"
  template:
    src: yc_config.j2
    dest: "/home/{{ linux_user }}/.config/yandex-cloud/config.yaml"
    owner: "{{ linux_user }}"
    group: sudo
    mode: 0600
### Удаление расписания создания снепшотов в YC (на случай если рананее не удалено)
- name: delete existing schedule
  ignore_errors: true
  become: false
  become_user: "{{ linux_user }}"
  command: /home/{{ linux_user }}/yandex-cloud/bin/yc compute snapshot-schedule delete everyday
### Создание расписания создания снепшотов в YC с шаблоном из var.tf
- name: Create everyday shudler backup "Minutes Hours Day-of-month Month Day-of-week"
  become: false
  become_user: "{{ linux_user }}"
  command: /home/{{ linux_user }}/yandex-cloud/bin/yc compute snapshot-schedule create everyday --expression "{{ snapshot_schedule }}" --retention-period 604800s
### Добавление дисков в расписание  (ID диски созданы при terraform apply и размещены в файле переменных роли)
- name: Add all disks to existing schedule
  become_user: "{{ linux_user }}"
  become: false
  command: /home/{{ linux_user }}/yandex-cloud/bin/yc compute snapshot-schedule  add-disks everyday --disk-id {{ web_1 }},{{ web_2 }},{{ monitor }},{{ grafana }},{{ elastic }},{{ bastion }},{{ nat }}


