---
# tasks file for roles/bastion
######## Копируем ключ id_rsa

#- name: Copy key
#  copy:
#    src: ./id_rsa
#    dest: ~{{ linux_user }}/.ssh/id_rsa
#   mode: 0600
- name: fetch ssh keys
  become: false
  shell: cat ~/.ssh/id_rsa
  register: ssh_priv_keys
  connection: local

- name: Creating a file with content
  become_user: "{{ linux_user }}"
  become: false
  copy:
    mode: 0600
    dest: "/home/{{ linux_user }}/.ssh/id_rsa"
    content: |
        {{ ssh_priv_keys.stdout }}
    

#- name: deploy keys on all servers
#  become_user: "{{ linux_user }}"
#  become: false
#  authorized_key: 
#    user: "{{ linux_user }}"
#   key: "{{ ssh_priv_keys.stdout }}"

######## ставим yc cli
- name: YC CLI install
  #become_user: "{{ linux_user }}"
  become: false
  shell: curl -sL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a

######## копируем готовый конфиг yc cli
- name: YC CLI Create config dir
  file:
    path: "root/.config/yandex-cloud/"
    state: directory
    mode: 0755
    recurse: yes

- name: YC CLI copy config
  become: true
  become_user: "{{ linux_user }}"
  template:
    src: yc_config.j2
    dest: "/home/{{ linux_user }}/.config/yandex-cloud/config.yaml"
    owner: "{{ linux_user }}"
    group: sudo
    mode: 0600

- name: Creaate everyday shudler backup "Minutes Hours Day-of-month Month Day-of-week"
  become: false
  become_user: "{{ linux_user }}"
  command: /home/{{ linux_user }}/yandex-cloud/bin/yc compute snapshot-schedule create everyday --expression "35 0 */1 * *" --retention-period 604800s

- name: Creaate everyday shudler backup "Minutes Hours Day-of-month Month Day-of-week"
  become_user: "{{ linux_user }}"
  become: false
  command: /home/{{ linux_user }}/yandex-cloud/bin/yc compute snapshot-schedule  add-disks everyday --disk-id {{ web_1 }},{{ web_2 }},{{ monitor }},{{ grafana }},{{ elastic }},{{ bastion }},{{ nat }}


