---
### Установка Grafana https://grafana.com/grafana/download?pg=get&plcmt=selfmanaged-box1-cta1&edition=oss
- name: install gpg
  apt:
    name: adduser,libfontconfig1
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: download and install grafana.
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb
### Копирование файла конфигурации ресурсов DATA_SOURCE c ПРЕДОПРЕДЕЛЕННЫМ ID (в нашем случае uid: netology) 
### https://grafana.com/docs/grafana/latest/administration/provisioning/
- name: copy file dataresource to /etc/grafana/provisioning/datasources
  copy:
    src: "prometheus_ds.yaml"
    dest: "/etc/grafana/provisioning/datasources/prometheus_ds.yaml"
    owner: root
    group: grafana
    mode: 0660
### Копирование файла конфигурации DASH_BOARD для prometheus
### https://grafana.com/docs/grafana/latest/administration/provisioning/
- name: copy file dashboard config to /etc/grafana/provisioning/dashboards
  copy:
    src: "prometheus_db.yaml"
    dest: "/etc/grafana/provisioning/dashboards/prometheus_db.yaml"
    owner: root
    group: grafana
    mode: 0660
### Копирование ЗАРАНЕЕ созданного шаблона DASH_BOARD c ПРЕДОПРЕДЕЛЕННЫМ ID (в нашем случае uid: netology)
- name: copy file dashboard to /etc/grafana/provisioning/dashboards
  copy:
    src: "WEB.json"
    dest: "/etc/grafana/provisioning/dashboards/WEB.json"
    owner: root
    group: grafana
    mode: 0660
###  Запуск сервиса grafana
- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
### Ожидание доступности сервиса перед сменой пароля 
- name: "Check if Grafana is accessible."
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
##смена пароля админа (из файла vars.tf)
- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_password }}"