---
######## Установка Grafana
- name: install gpg
  apt:
    name: gnupg,software-properties-common,adduser,libfontconfig1
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: download and install grafana.
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb

- name: copy file dataresource to /etc/grafana/provisioning/datasources
  copy:
    src: "prometheus_ds.yaml"
    dest: "/etc/grafana/provisioning/datasources/prometheus_ds.yaml"
    owner: root
    group: grafana
    mode: 0660

- name: copy file dashboard config to /etc/grafana/provisioning/dashboards
  copy:
    src: "prometheus_db.yaml"
    dest: "/etc/grafana/provisioning/dashboards/prometheus_db.yaml"
    owner: root
    group: grafana
    mode: 0660
   
- name: copy file dashboard to /etc/grafana/provisioning/dashboards
  copy:
    src: "WEB.json"
    dest: "/etc/grafana/provisioning/dashboards/WEB.json"
    owner: root
    group: grafana
    mode: 0660

##Запуск сервиса 
- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes


##ждем поднятие сервиса
- name: "Check if Grafana is accessible."
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120


##смена пароля админа
- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0