---
# tasks file for roles/nginx-log-exporter
### Создание пользователя и группы для запуска сервиса prometheus-nginxlog-exporter
- name: create nginxlog-exporter user
  user:
    name: "{{ nginxlog_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
### Установка prometheus-nginxlog-exporter
- name: download and install Nginx Log Exporter.
  apt:
    deb: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.9.2/prometheus-nginxlog-exporter_1.9.2_linux_amd64.deb
### Добаление пользователя в группу ADM для чтения логов NGINX 
- name: Add nginxlog_exporter_user to ADM group
  user:
    name: "{{ nginxlog_exporter_user }}"
    groups: adm
    append: yes
### Смена прав запуска сервиса на созданные ранее
- name: Set up rights for service
  ini_file:
    dest: /lib/systemd/system/prometheus-nginxlog-exporter.service
    no_extra_spaces: yes
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: "User", value: "{{ nginxlog_exporter_user }}" }
    - { option: "Group", value: "{{ nginxlog_exporter_group }}" }
  notify: reload_prometheus-nginxlog-exporter
